//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class BoolPointer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BoolPointer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BoolPointer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BoolPointer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          swiglibPINVOKE.delete_BoolPointer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public BoolPointer() : this(swiglibPINVOKE.new_BoolPointer(), true) {
  }

  public void assign(bool value) {
    swiglibPINVOKE.BoolPointer_assign(swigCPtr, value);
  }

  public bool value() {
    bool ret = swiglibPINVOKE.BoolPointer_value(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_bool cast() {
    global::System.IntPtr cPtr = swiglibPINVOKE.BoolPointer_cast(swigCPtr);
    SWIGTYPE_p_bool ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_bool(cPtr, false);
    return ret;
  }

  public static BoolPointer frompointer(SWIGTYPE_p_bool t) {
    global::System.IntPtr cPtr = swiglibPINVOKE.BoolPointer_frompointer(SWIGTYPE_p_bool.getCPtr(t));
    BoolPointer ret = (cPtr == global::System.IntPtr.Zero) ? null : new BoolPointer(cPtr, false);
    return ret;
  }

}
