//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Fooector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<FooObject>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Fooector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Fooector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Fooector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          swiglibPINVOKE.delete_Fooector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Fooector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (FooObject element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public FooObject this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(FooObject[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(FooObject[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, FooObject[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<FooObject> global::System.Collections.Generic.IEnumerable<FooObject>.GetEnumerator() {
    return new FooectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new FooectorEnumerator(this);
  }

  public FooectorEnumerator GetEnumerator() {
    return new FooectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class FooectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<FooObject>
  {
    private Fooector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public FooectorEnumerator(Fooector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public FooObject Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (FooObject)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    swiglibPINVOKE.Fooector_Clear(swigCPtr);
  }

  public void Add(FooObject x) {
    swiglibPINVOKE.Fooector_Add(swigCPtr, FooObject.getCPtr(x));
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = swiglibPINVOKE.Fooector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = swiglibPINVOKE.Fooector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    swiglibPINVOKE.Fooector_reserve(swigCPtr, n);
  }

  public Fooector() : this(swiglibPINVOKE.new_Fooector__SWIG_0(), true) {
  }

  public Fooector(Fooector other) : this(swiglibPINVOKE.new_Fooector__SWIG_1(Fooector.getCPtr(other)), true) {
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  public Fooector(int capacity) : this(swiglibPINVOKE.new_Fooector__SWIG_2(capacity), true) {
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  private FooObject getitemcopy(int index) {
    FooObject ret = new FooObject(swiglibPINVOKE.Fooector_getitemcopy(swigCPtr, index), true);
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private FooObject getitem(int index) {
    FooObject ret = new FooObject(swiglibPINVOKE.Fooector_getitem(swigCPtr, index), false);
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, FooObject val) {
    swiglibPINVOKE.Fooector_setitem(swigCPtr, index, FooObject.getCPtr(val));
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(Fooector values) {
    swiglibPINVOKE.Fooector_AddRange(swigCPtr, Fooector.getCPtr(values));
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  public Fooector GetRange(int index, int count) {
    global::System.IntPtr cPtr = swiglibPINVOKE.Fooector_GetRange(swigCPtr, index, count);
    Fooector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Fooector(cPtr, true);
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, FooObject x) {
    swiglibPINVOKE.Fooector_Insert(swigCPtr, index, FooObject.getCPtr(x));
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, Fooector values) {
    swiglibPINVOKE.Fooector_InsertRange(swigCPtr, index, Fooector.getCPtr(values));
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    swiglibPINVOKE.Fooector_RemoveAt(swigCPtr, index);
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    swiglibPINVOKE.Fooector_RemoveRange(swigCPtr, index, count);
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Fooector Repeat(FooObject value, int count) {
    global::System.IntPtr cPtr = swiglibPINVOKE.Fooector_Repeat(FooObject.getCPtr(value), count);
    Fooector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Fooector(cPtr, true);
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    swiglibPINVOKE.Fooector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    swiglibPINVOKE.Fooector_Reverse__SWIG_1(swigCPtr, index, count);
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, Fooector values) {
    swiglibPINVOKE.Fooector_SetRange(swigCPtr, index, Fooector.getCPtr(values));
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
  }

}
