//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IntArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IntArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IntArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IntArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          swiglibPINVOKE.delete_IntArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public IntArray(int nelements) : this(swiglibPINVOKE.new_IntArray(nelements), true) {
  }

  public int getitem(int index) {
    int ret = swiglibPINVOKE.IntArray_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, int value) {
    swiglibPINVOKE.IntArray_setitem(swigCPtr, index, value);
  }

  public SWIGTYPE_p_int cast() {
    global::System.IntPtr cPtr = swiglibPINVOKE.IntArray_cast(swigCPtr);
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    return ret;
  }

  public static IntArray frompointer(SWIGTYPE_p_int t) {
    global::System.IntPtr cPtr = swiglibPINVOKE.IntArray_frompointer(SWIGTYPE_p_int.getCPtr(t));
    IntArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new IntArray(cPtr, false);
    return ret;
  }

}
