//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TestSwig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TestSwig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TestSwig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TestSwig() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          swiglibPINVOKE.delete_TestSwig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static int Add(int a, int b) {
    int ret = swiglibPINVOKE.TestSwig_Add(a, b);
    return ret;
  }

  public int UseFoo(SWIGTYPE_p_FooObject obj) {
    int ret = swiglibPINVOKE.TestSwig_UseFoo(swigCPtr, SWIGTYPE_p_FooObject.getCPtr(obj));
    if (swiglibPINVOKE.SWIGPendingException.Pending) throw swiglibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public TestSwig() : this(swiglibPINVOKE.new_TestSwig(), true) {
  }

}
